In [3]:
import numpy as np

[문제-1] 길이가 10인 0-벡터를 만드세요.

In [161]:
a = np.zeros(10, dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [200]:
a = np.zeros(10, dtype=int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [163]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[문제-4] 위 벡터의 순서를 바꾸세요.

In [165]:
print(a[::-1])
print(np.arange(49, 9, -1))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [18]:
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [172]:
a = np.array([1, 2, 0, 0, 4, 0])
print(a[a != 0])
print(a[np.where(a != 0)])

[1 2 4]
[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [188]:
print(np.identity(3, dtype=int))
print(np.eye(3, dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [197]:
a = np.random.rand(3, 3) # 어차피 0~1이라 범위 지정 안해도됨
print(a)

[[0.31 0.06 0.72]
 [0.9  0.1  0.56]
 [0.41 0.24 0.65]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [193]:
# amax: 주어진 축을 따라 배열의 최대값을 반환
print(np.amax(a))
print(np.amin(a))

0.7979989828041781
0.055684304789930916


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [195]:
np.set_printoptions(suppress=True, precision=2) # precision: 소수점 자리

In [199]:
row_avg = np.mean(a, axis=1)
print(f'행 평균 : {row_avg}')
col_avg = np.mean(a, axis=0)
print(f'열 평균 : {col_avg}')

행 평균 : [0.36 0.52 0.43]
열 평균 : [0.54 0.13 0.65]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [187]:
print(np.identity(5, dtype=int))
print(np.eye(5, dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [208]:
a = np.random.randint(10, 51, size=9) # numpy의 randint는 end값 포함X
print(a)

[24 14 32 14 32 44 30 24 32]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [213]:
a = a.reshape(3, 3)
print(a)

[[24 14 32]
 [14 32 44]
 [30 24 32]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [214]:
print(np.sum(a, axis=1))

[70 90 86]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [221]:
print(np.max(a, axis=0))

[30 32 44]
[30 32 44]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [224]:
print(np.mean(a))

27.333333333333332


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [225]:
# a = np.random.randint(1, 11, size=6).reshape(2, 3)
a = np.random.randint(1, 11, (2, 3))
print(a)

[[ 7  7 10]
 [ 7  2  4]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [226]:
# b = np.random.randint(10, 21, size=6).reshape(3, 2)
b = np.random.randint(10, 21, (3, 2))
print(b)

[[19 19]
 [18 17]
 [15 16]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [228]:
c = np.matmul(a, b)
c = a @ b
print(c)

[[409 412]
 [229 231]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [233]:
print(c.T)
print(np.transpose(c))

[[409 229]
 [412 231]]
[[409 229]
 [412 231]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [158]:
nums = np.arange(1, 47)
a = np.random.choice(nums, size=6, replace=False)
print(a)

[45 19 25 14 37 29]
