# Numpy

In [2]:
import numpy as np

## 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성하고 각 행의 첫 번째 값으로 정렬하시오. (5점)

In [4]:
r = np.random.randint(0, 10, (3, 3))
print(r)
print(r[r[:, 0].argsort()])

[[6 6 6]
 [4 5 4]
 [0 6 0]]
[[0 6 0]
 [4 5 4]
 [6 6 6]]


## 8x8 모양의 정수 0으로 채워진 행렬을 만들고 다음과 인덱싱과 슬라이싱일 이용하여 다음과 같은 체크보드 패턴을만드시오. (10점)

In [8]:
r = np.zeros((8, 8), dtype=int)
r[1::2, ::2] = 1
r[::2, 1::2] = 1
print(r)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 ## (0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꾸는 코드를 만드시오. (5점)

In [11]:
r = np.random.rand(10)
print(r)

r[r.argmax()] = 0
# r[r.max() == r] = 0 
print(r)

[0.32919513 0.20419195 0.62637003 0.82977871 0.45249424 0.91986935
 0.92167321 0.34420138 0.91919181 0.39405809]
[0.32919513 0.20419195 0.62637003 0.82977871 0.45249424 0.91986935
 0.         0.34420138 0.91919181 0.39405809]


# Pandas

In [14]:
import numpy as np
import pandas as pd

## 월드컵 출전선수 골 기록 데이터 분석 (30점)
- 분석 내용
    - ① 주어진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
    - ② 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.
    - ③ Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케이스가 존재한다. 
        해당 건은 몇 건인지 출력하시오.
    - ④ 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
        전체 데이터 행의 숫자를 출력하시오
    - ⑤ 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.
    - ⑥ yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
    - ⑦ 2002년도에 출전한 전체 선수 수를 구하시오.
    - ⑧ 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [15]:
data = pd.read_csv('worldcupgoals.csv')

In [16]:
data.head()

Player  Goals                Years  Country
0  Miroslav Klose     16  2002-2006-2010-2014  Germany
1         Ronaldo     15       1998-2002-2006   Brazil
2     Gerd Muller     14            1970-1974  Germany
3   Just Fontaine     13                 1958   France
4            Pele     12  1958-1962-1966-1970   Brazil

① 주어진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오

In [29]:
grouped = data.groupby('Country')[['Goals']].sum()
grouped.sort_values('Goals', ascending=False).head(5)

Goals
Country         
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115

② 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.

In [30]:
grouped = data.groupby('Country')

In [32]:
grouped = data.groupby(['Country'])[['Goals']].sum()
grouped.sort_values('Goals', ascending=False, inplace=True)
print(grouped.head(5))

           Goals
Country         
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115


In [11]:
grouped = data.groupby(['Country']).sum().sort_values('Goals', ascending=False).head(5)
print(grouped)

           Goals
Country         
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115


③ Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케이스가 존재한다. 해당 건은 몇 건인지 출력하시오.

In [46]:
data[data['Years'].isin(['-'])]

Empty DataFrame
Columns: [Player, Goals, Years, Country]
Index: []

In [12]:
date = data['Years']
len(date) < 4
# data[np.logical_not(date.isin(['-']), ) ]

False

④ 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고 전체 데이터 행의 숫자를 출력하시오

⑤ 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.

In [ ]:
data['LenCup']

⑥ Yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.

In [273]:
yugo = data[data['Country'] == 'Yugoslavia']
yugo['Years']

158               1962
250               1974
251               1930
252               1962
253     1990-1998-2002
254          1990-1998
255               1958
491               1950
492               1990
493               1974
494               1998
495               1990
496               1958
497          1974-1982
498               1950
1272         1950-1954
1273              1974
1274              1974
1275              1982
1276              1974
1277              1930
1278              1962
1279              1998
1280              1998
1281         1954-1958
1282              1974
1283              1950
1284              1958
1285              1974
1286         1974-1982
1287              1962
1288              1958
1289              1930
1290              1962
1291         1982-1990
1292              1930
1293              1930
1294         1954-1958
Name: Years, dtype: object

⑦ 2002년도에 출전한 전체 선수 수를 구하시오.

In [13]:
data['Years'].isin(['2002']).sum()

46

⑧ 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [ ]:
one = data[len(data['Years']) == 4]
grouped = data.groupby('Player')[['Player', 'Goals']].sum()
grouped

## 전 세계 행복도 지수 데이터 분석 (30점)
- 분석 내용
    - ① 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.
    - ② 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.
    - ③ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.
    - ④ 2019년 데이터- 를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을
        각각 구하고 그 차이 값을 출력하시오
    - ⑤ 각 년도의 부패에 대한인식을 내림차순 정렬했을 때 상위 20개 국가의 부패에 대한인식의 평균을 구하시오.
    - ⑥ 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하시오.
    - ⑦ 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

In [283]:
data = pd.read_csv('happiness.csv')

In [193]:
data

행복랭킹                       나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도  \
0       1                   Finland  7.769  1.340  1.587  0.986    0.596   
1       2                   Denmark  7.600  1.383  1.573  0.996    0.592   
2       3                    Norway  7.554  1.488  1.582  1.028    0.603   
3       4                   Iceland  7.494  1.380  1.624  1.026    0.591   
4       5               Netherlands  7.488  1.396  1.522  0.999    0.557   
..    ...                       ...    ...    ...    ...    ...      ...   
307   152                     Yemen  3.355  0.442  1.073  0.343    0.244   
308   153                  Tanzania  3.303  0.455  0.991  0.381    0.481   
309   154               South Sudan  3.254  0.337  0.608  0.177    0.112   
310   155  Central African Republic  3.083  0.024  0.000  0.010    0.305   
311   156                   Burundi  2.905  0.091  0.627  0.145    0.065   

       관대함  부패에 대한인식    년도  
0    0.153     0.393  2019  
1    0.252     0.410  2019  
2    0.271     0.341  2019  
3    0.354     0.118  2019  
4    0.322     0.298  2019  
..     ...       ...   ...  
307  0.083     0.064  2018  
308  0.270     0.097  2018  
309  0.224     0.106  2018  
310  0.218     0.038  2018  
311  0.149     0.076  2018  

[312 rows x 10 columns]

① 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.

In [195]:
# 2018년 1~10위 행복점수 평균
data['점수'][data['년도'] == 2018].head(10).mean()

7.4442

In [196]:
# 2019년 1~10위 행복점수 평균
data['점수'][data['년도'] == 2019].head(10).mean()

7.4559000000000015

② 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.

In [208]:
a = data.groupby('년도')[['점수']].mean()
a
data.pivot_table(index='년도', values=['점수'], aggfunc='mean')

점수
년도            
2018  5.375917
2019  5.407096

③ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.

In [209]:
print('2018년 하위 5개국 행복점수 평균')
print(data['점수'][data['년도'] == 2018].tail(5).mean())
print()

print('2019년 하위 5개국 행복점수 평균')
print(data['점수'][data['년도'] == 2019].tail(5).mean())

2018년 하위 5개국 행복점수 평균
3.1799999999999997

2019년 하위 5개국 행복점수 평균
3.1407999999999996


④ 2019년 데이터를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을 각각 구하고 그 차이 값을 출력하시오

In [239]:
data_2019 = data[data['년도'] == 2019]
gdp_mean = data_2019['상대GDP'].mean()

print('2019년 상대 GDP 평균 이상 나라들의 행복점수 평균')
print(data_2019['점수'][data_2019['상대GDP'] > gdp_mean].mean())

print('2019년 상대 GDP 평균 이하 나라들의 행복점수 평균')
print(data_2019['점수'][data_2019['상대GDP'] < gdp_mean].mean())

print('차이')
print(data_2019['점수'][data_2019['상대GDP'] > gdp_mean].mean() - data_2019['점수'][data_2019['상대GDP'] < gdp_mean].mean())

2019년 상대 GDP 평균 이상 나라들의 행복점수 평균
6.013204545454547
2019년 상대 GDP 평균 이하 나라들의 행복점수 평균
4.6227205882352935
차이
1.3904839572192538


⑤ 각 년도의 부패에 대한인식을 내림차순 정렬했을 때 상위 20개 국가의 부패에 대한인식의 평균을 구하시오.

In [211]:
a = data.sort_values('부패에 대한인식').head(20)
a.pivot_table(index='년도', values=['부패에 대한인식'], aggfunc='mean')

부패에 대한인식
년도            
2018  0.010636
2019  0.009000

⑥ 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하시오.

In [219]:
a = data[np.logical_and(data['년도'] == 2018, data['행복랭킹'] <= 50)]

b = data[np.logical_and(data['년도'] == 2019, data['행복랭킹'] > 50)]

c = a['나라명'].isin(b['나라명']).sum()
print(c)

3


⑦ 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

## 유튜브 데이터 분석 (20점)
- 분석 내용
    - ① 컬럼의 이름을 다음과 같이 변경하시오
        ◼title : 채널명, category : 카테고리, subscriber : 구독자수, view : 조회수, video : 영상개수
    - ② ‘구독자수’ 컬럼과 ‘조회수’ 컬럼의 타입을 정수형(int64)로 변경하시오 (‘억’,’만’ 한글을 삭제 후 숫자로 변경)
    - ③ ‘영상개수’ 컬럼의 ‘,’와 ‘개’문자를 제거하고 정수형(int32)로 변경하시오.
    - ④ 인기 채널 확인하기
        ◼’구독자수’와 ‘조회수’가 많은 5개의 채널을 각각 출력하시오.
    - ⑤ ‘카테고리’가 [음악/댄스/가수]인 채널의 ‘구독자수’ 상위 5개를 출력하시오.
    - ⑥ ‘카테고리가’ [TV/방송]이거나 [게임]인 채널의 개수를 출력하시오.
    - ⑦ ‘채널명’에 ‘KBS’가 포함된 채널 명을 출력하시오.
    - ⑧ ‘카테고리’별 ‘구독자수’, ‘조회수’, ‘영상개수’의 평균을 출력하시오.

In [287]:
data = pd.read_csv('youtube_rank.csv')

In [288]:
data

title    category subscriber       view    video
0                      BLACKPINK  [음악/댄스/가수]      5140만  128억5130만     319개
1                 Big Hit Labels  [음악/댄스/가수]      4550만  120억8966만     433개
2                      BANGTANTV  [음악/댄스/가수]      3870만   54억7598만   1,319개
3    Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]      2650만  110억5288만     223개
4                         SMTOWN  [음악/댄스/가수]      2450만  180억7532만   3,583개
..                           ...         ...        ...        ...      ...
995                Ranking World       [미분류]        40만    1억2752만     503개
996                         급식걸즈    [취미/라이프]        40만    2억3901만     226개
997                          OCN     [TV/방송]        40만    3억4583만  10,071개
998                Bravo jamoasi       [미분류]        40만      6193만      25개
999                  덕출 : DCTVGO     [TV/방송]        40만      8249만     202개

[1000 rows x 5 columns]

① 컬럼의 이름을 다음과 같이 변경하시오


In [289]:
data.columns = ['채널명', '카테고리', '구독자수', '조회수', '영상개수']
data.columns

Index(['채널명', '카테고리', '구독자수', '조회수', '영상개수'], dtype='object')

② ‘구독자수’ 컬럼과 ‘조회수’ 컬럼의 타입을 정수형(int64)로 변경하시오 (‘억’,’만’ 한글을 삭제 후 숫자로 변경)

In [290]:
data['구독자수'] = data['구독자수'].str.replace('만', '', regex=False)
data['구독자수'] = data['구독자수'].str.replace('억', '', regex=False)
data['조회수'] = data['조회수'].str.replace('만', '', regex=False)
data['조회수'] = data['조회수'].str.replace('억', '', regex=False)

data['구독자수'] = data['구독자수'].astype('int64')
data['조회수'] = data['조회수'].astype('int64')

③ ‘영상개수’ 컬럼의 ‘,’와 ‘개’문자를 제거하고 정수형(int32)로 변경하시오.

In [291]:
data['영상개수'] = data['영상개수'].str.replace(',', '', regex=False)
data['영상개수'] = data['영상개수'].str.replace('개', '', regex=False)
data['영상개수'] = data['영상개수'].astype('int32')

④ 인기 채널 확인하기
    ◼’구독자수’와 ‘조회수’가 많은 5개의 채널을 각각 출력하시오.

In [292]:
data.sort_values('구독자수', ascending=False).head(5)

채널명        카테고리  구독자수      조회수  영상개수
0                    BLACKPINK  [음악/댄스/가수]  5140  1285130   319
1               Big Hit Labels  [음악/댄스/가수]  4550  1208966   433
2                    BANGTANTV  [음악/댄스/가수]  3870   547598  1319
3  Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  2650  1105288   223
4                       SMTOWN  [음악/댄스/가수]  2450  1807532  3583

In [293]:
data.sort_values('조회수', ascending=False).head(5)

채널명        카테고리  구독자수      조회수   영상개수
4            SMTOWN  [음악/댄스/가수]  2450  1807532   3583
6      1theK (원더케이)  [음악/댄스/가수]  2090  1786042  13291
8  ArianaGrandeVevo  [음악/댄스/가수]  1820  1479692    112
0         BLACKPINK  [음악/댄스/가수]  5140  1285130    319
1    Big Hit Labels  [음악/댄스/가수]  4550  1208966    433

⑤ ‘카테고리’가 [음악/댄스/가수]인 채널의 ‘구독자수’ 상위 5개를 출력하시오.

In [294]:
data[data['카테고리'] == '[음악/댄스/가수]'].sort_values('구독자수', ascending=False).head(5)

채널명        카테고리  구독자수      조회수  영상개수
0              BLACKPINK  [음악/댄스/가수]  5140  1285130   319
1         Big Hit Labels  [음악/댄스/가수]  4550  1208966   433
2              BANGTANTV  [음악/댄스/가수]  3870   547598  1319
4                 SMTOWN  [음악/댄스/가수]  2450  1807532  3583
5  1MILLION Dance Studio  [음악/댄스/가수]  2230   575358  2205

⑥ ‘카테고리가’ [TV/방송]이거나 [게임]인 채널의 개수를 출력하시오.

In [295]:
category = data[np.logical_or(data['카테고리'] == '[TV/방송]', data['카테고리'] == '[게임]')]
print('카테고리가 [TV/방송]이거나 [게임]인 채널의 개수')
print(len(category))

카테고리가 [TV/방송]이거나 [게임]인 채널의 개수
262


⑦ ‘채널명’에 ‘KBS’가 포함된 채널 명을 출력하시오

In [24]:
data[data['채널명'].isin(['KBS'])]

Empty DataFrame
Columns: [채널명, 카테고리, 구독자수, 조회수, 영상개수]
Index: []

⑧ ‘카테고리’별 ‘구독자수’, ‘조회수’, ‘영상개수’의 평균을 출력하시오.

In [296]:
data.groupby('카테고리')[['구독자수', '조회수', '영상개수']].mean().round(2)

구독자수        조회수      영상개수
카테고리                                    
[BJ/인물/연예인]  127.44   41015.49    837.74
[IT/기술/컴퓨터]   80.62   17661.00   1200.12
[TV/방송]      121.99   71848.34   9025.13
[게임]          74.36   45425.35   2527.01
[교육/강의]       85.13   17721.83    837.91
[국내/해외/여행]    62.60   18662.40    830.20
[뉴스/정치/사회]   122.70  119993.55  42048.09
[미분류]        142.95   40903.40    778.05
[스포츠/운동]      93.25   27918.92   3954.92
[애완/반려동물]    116.10   42131.70    786.25
[영화/만화/애니]    85.27   31858.70    770.18
[음식/요리/레시피]  161.20   40738.19    830.02
[음악/댄스/가수]   319.52  109166.85   1382.05
[자동차]         49.00   18561.50    670.00
[주식/경제/부동산]   62.60    6800.00   1026.40
[취미/라이프]      97.45   20431.18    359.32
[취미]          56.00   10615.00    237.00
[키즈/어린이]     272.92  128138.43   1069.16
[패션/미용]       82.39   10437.74    313.16
[해외]         159.50   83825.33   5043.50
[회사/오피셜]     220.25   49661.25   2084.25