위 : 선생님 풀이<br>
아래 : 내 풀이

# Numpy

In [2]:
import numpy as np

## 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성하고 각 행의 첫 번째 값으로 정렬하시오. (5점)

In [4]:
r = np.random.randint(0, 10, (3, 3))
print(r)
print(r[r[:, 0].argsort()])

[[6 6 6]
 [4 5 4]
 [0 6 0]]
[[0 6 0]
 [4 5 4]
 [6 6 6]]


## 8x8 모양의 정수 0으로 채워진 행렬을 만들고 다음과 인덱싱과 슬라이싱일 이용하여 다음과 같은 체크보드 패턴을만드시오. (10점)

In [8]:
r = np.zeros((8, 8), dtype=int)
r[1::2, ::2] = 1
r[::2, 1::2] = 1
print(r)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 ## (0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꾸는 코드를 만드시오. (5점)

In [11]:
r = np.random.rand(10)
print(r)

r[r.argmax()] = 0
# r[r.max() == r] = 0 
print(r)

[0.32919513 0.20419195 0.62637003 0.82977871 0.45249424 0.91986935
 0.92167321 0.34420138 0.91919181 0.39405809]
[0.32919513 0.20419195 0.62637003 0.82977871 0.45249424 0.91986935
 0.         0.34420138 0.91919181 0.39405809]


# Pandas

In [14]:
import numpy as np
import pandas as pd

In [53]:
# 경고 메세지 출력 제거
import warnings
warnings.filterwarnings(action='ignore')

## 월드컵 출전선수 골 기록 데이터 분석 (30점)
- 분석 내용
    - ① 주어진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
    - ② 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.
    - ③ Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케이스가 존재한다. 
        해당 건은 몇 건인지 출력하시오.
    - ④ 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
        전체 데이터 행의 숫자를 출력하시오
    - ⑤ 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.
    - ⑥ yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
    - ⑦ 2002년도에 출전한 전체 선수 수를 구하시오.
    - ⑧ 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [87]:
data = pd.read_csv('worldcupgoals.csv')

In [88]:
data

Player  Goals                Years     Country
0          Miroslav Klose     16  2002-2006-2010-2014     Germany
1                 Ronaldo     15       1998-2002-2006      Brazil
2             Gerd Muller     14            1970-1974     Germany
3           Just Fontaine     13                 1958      France
4                    Pele     12  1958-1962-1966-1970      Brazil
...                   ...    ...                  ...         ...
1290        Josip Skoblar      1                 1962  Yugoslavia
1291          Safet Susic      1            1982-1990  Yugoslavia
1292  Aleksandar Tirnanic      1                 1930  Yugoslavia
1293  Djordje Vujadinovic      1                 1930  Yugoslavia
1294         Branko Zebec      1            1954-1958  Yugoslavia

[1295 rows x 4 columns]

① 주어진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오

In [24]:
data.groupby(['Country'])[['Goals']].sum().sort_values('Goals', ascending=False).head(5)

Goals
Country         
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115

② 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.

In [29]:
data.groupby(['Country'])[['Player']].count().sort_values('Player', ascending=False).head(5)

Player
Country          
Brazil         81
Germany        78
Italy          60
Argentina      59
France         58

③ Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케이스가 존재한다. 해당 건은 몇 건인지 출력하시오.

In [37]:
count = 0
for years in data['Years']:
    for year in years.split('-'):
        if len(year) != 4:
            count += 1
            
print(f'{count}건')

45건


④ 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고 전체 데이터 행의 숫자를 출력하시오

In [47]:
def checkYearFormat(years):
    for year in years.split('-'):
        if len(year) != 4:
            return False
    return True

data['year_check'] = data['Years'].apply(lambda x : checkYearFormat(x))
check = data['year_check'] == False
check.sum()

df_new = data[data['year_check']]
df_new.shape[0]

1250

⑤ 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.

In [62]:
df_new['LenCup'] = [ len(years.split('-')) for years in df_new['Years']]
len(df_new[df_new['LenCup'] == 4])

16

⑥ Yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.

In [60]:
len(df_new[df_new['Country'] == 'Yugoslavia'][df_new['LenCup'] == 2])

7

⑦ 2002년도에 출전한 전체 선수 수를 구하시오.

In [66]:
len(df_new[df_new['Years'].str.contains('2002')])

156

⑧ 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [76]:
df_new[df_new['LenCup'] == 1].sort_values('Goals', ascending=False).head(1)[['Player', 'Goals']]

Player  Goals
3  Just Fontaine     13

## 전 세계 행복도 지수 데이터 분석 (30점)
- 분석 내용
    - ① 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.
    - ② 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.
    - ③ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.
    - ④ 2019년 데이터- 를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을
        각각 구하고 그 차이 값을 출력하시오
    - ⑤ 각 년도의 부패에 대한인식을 내림차순 정렬했을 때 상위 20개 국가의 부패에 대한인식의 평균을 구하시오.
    - ⑥ 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하시오.
    - ⑦ 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

In [89]:
data = pd.read_csv('happiness.csv')

In [90]:
data

행복랭킹                       나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도  \
0       1                   Finland  7.769  1.340  1.587  0.986    0.596   
1       2                   Denmark  7.600  1.383  1.573  0.996    0.592   
2       3                    Norway  7.554  1.488  1.582  1.028    0.603   
3       4                   Iceland  7.494  1.380  1.624  1.026    0.591   
4       5               Netherlands  7.488  1.396  1.522  0.999    0.557   
..    ...                       ...    ...    ...    ...    ...      ...   
307   152                     Yemen  3.355  0.442  1.073  0.343    0.244   
308   153                  Tanzania  3.303  0.455  0.991  0.381    0.481   
309   154               South Sudan  3.254  0.337  0.608  0.177    0.112   
310   155  Central African Republic  3.083  0.024  0.000  0.010    0.305   
311   156                   Burundi  2.905  0.091  0.627  0.145    0.065   

       관대함  부패에 대한인식    년도  
0    0.153     0.393  2019  
1    0.252     0.410  2019  
2    0.271     0.341  2019  
3    0.354     0.118  2019  
4    0.322     0.298  2019  
..     ...       ...   ...  
307  0.083     0.064  2018  
308  0.270     0.097  2018  
309  0.224     0.106  2018  
310  0.218     0.038  2018  
311  0.149     0.076  2018  

[312 rows x 10 columns]

① 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.

In [93]:
data[data['행복랭킹'] <= 10].groupby('년도')['점수'].mean()

년도
2018    7.4442
2019    7.4559
Name: 점수, dtype: float64

In [96]:
# 그룹핑 먼저 했을 때
groued = data.groupby('년도')
for year, group in groued:
    print(year, '년도: ', end=' ')
    print(group[group['행복랭킹'] <= 10]['점수'].mean())

2018 년도:  7.4442
2019 년도:  7.4559000000000015


② 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.

In [105]:
data[data['행복랭킹'] <= 50].groupby(['년도', '나라명'])[['점수']].mean()

점수
년도   나라명                        
2018 Argentina             6.388
     Australia             7.272
     Austria               7.139
     Bahrain               6.105
     Belgium               6.927
...                          ...
2019 United Arab Emirates  6.825
     United Kingdom        7.054
     United States         6.892
     Uruguay               6.293
     Uzbekistan            6.174

[100 rows x 1 columns]

In [101]:
# data[data['행복랭킹'] <= 50].groupby(['년도', '나라명'])[['점수']].mean()
data[data['행복랭킹'] <= 50].groupby(['년도'])[['점수']].mean()

점수
년도           
2018  6.64678
2019  6.67002

③ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.

In [117]:
data.sort_values(['년도', '점수']).groupby('년도').head(5).groupby('년도')['점수'].mean()

년도
2018    3.1800
2019    3.1408
Name: 점수, dtype: float64

In [209]:
print('2018년 하위 5개국 행복점수 평균')
print(data['점수'][data['년도'] == 2018].tail(5).mean())
print()

print('2019년 하위 5개국 행복점수 평균')
print(data['점수'][data['년도'] == 2019].tail(5).mean())

2018년 하위 5개국 행복점수 평균
3.1799999999999997

2019년 하위 5개국 행복점수 평균
3.1407999999999996


④ 2019년 데이터를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을 각각 구하고 그 차이 값을 출력하시오

In [125]:
df_2019 = data[data['년도'] == 2019]
over_mean = df_2019[df_2019['상대GDP'] >= df_2019['상대GDP'].mean()]['점수'].mean()
under_mean = df_2019[df_2019['상대GDP'] < df_2019['상대GDP'].mean()]['점수'].mean()

print('over_mean:', over_mean)
print('under_mean:', under_mean)
print(over_mean - under_mean)

over_mean: 6.013204545454547
under_mean: 4.6227205882352935
1.3904839572192538


In [239]:
data_2019 = data[data['년도'] == 2019]
gdp_mean = data_2019['상대GDP'].mean()

print('2019년 상대 GDP 평균 이상 나라들의 행복점수 평균')
print(data_2019['점수'][data_2019['상대GDP'] > gdp_mean].mean())

print('2019년 상대 GDP 평균 이하 나라들의 행복점수 평균')
print(data_2019['점수'][data_2019['상대GDP'] < gdp_mean].mean())

print('차이')
print(data_2019['점수'][data_2019['상대GDP'] > gdp_mean].mean() - data_2019['점수'][data_2019['상대GDP'] < gdp_mean].mean())

2019년 상대 GDP 평균 이상 나라들의 행복점수 평균
6.013204545454547
2019년 상대 GDP 평균 이하 나라들의 행복점수 평균
4.6227205882352935
차이
1.3904839572192538


⑤ 각 년도의 부패에 대한인식을 내림차순 정렬했을 때 상위 20개 국가의 부패에 대한인식의 평균을 구하시오.

In [130]:
data.sort_values(['년도', '부패에 대한인식'], ascending=False).groupby('년도').head(20).groupby('년도')['부패에 대한인식'].mean()

년도
2018    0.3267
2019    0.3201
Name: 부패에 대한인식, dtype: float64

In [126]:
data.sort_values('부패에 대한인식').head(20)
data.pivot_table(index='년도', values=['부패에 대한인식'], aggfunc='mean')

부패에 대한인식
년도            
2018  0.112000
2019  0.110603

⑥ 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하시오.

In [142]:
df1 = data[np.logical_and(data['년도'] == 2018, data['행복랭킹'] <= 50)]['나라명']
df2 =  data[np.logical_and(data['년도'] == 2019, data['행복랭킹'] > 50)]['나라명']

df2.isin(df1).sum()
df2[df2.isin(df1)]

50      Kuwait
51    Thailand
79    Malaysia
Name: 나라명, dtype: object

In [219]:
a = data[np.logical_and(data['년도'] == 2018, data['행복랭킹'] <= 50)]
b = data[np.logical_and(data['년도'] == 2019, data['행복랭킹'] > 50)]

c = a['나라명'].isin(b['나라명']).sum()
print(c)

3


⑦ 2018년, 2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

In [165]:
year_2018 = data[data['년도'] == 2018]['나라명']
year_2019 = data[data['년도'] == 2019]['나라명']
year_2018_2019 = year_2019[year_2019.isin(year_2018)]

In [149]:
multiple = data[data['나라명'].isin(year_2018_2019)]
multiple

행복랭킹                       나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도  \
0       1                   Finland  7.769  1.340  1.587  0.986    0.596   
1       2                   Denmark  7.600  1.383  1.573  0.996    0.592   
2       3                    Norway  7.554  1.488  1.582  1.028    0.603   
3       4                   Iceland  7.494  1.380  1.624  1.026    0.591   
4       5               Netherlands  7.488  1.396  1.522  0.999    0.557   
..    ...                       ...    ...    ...    ...    ...      ...   
307   152                     Yemen  3.355  0.442  1.073  0.343    0.244   
308   153                  Tanzania  3.303  0.455  0.991  0.381    0.481   
309   154               South Sudan  3.254  0.337  0.608  0.177    0.112   
310   155  Central African Republic  3.083  0.024  0.000  0.010    0.305   
311   156                   Burundi  2.905  0.091  0.627  0.145    0.065   

       관대함  부패에 대한인식    년도  
0    0.153     0.393  2019  
1    0.252     0.410  2019  
2    0.271     0.341  2019  
3    0.354     0.118  2019  
4    0.322     0.298  2019  
..     ...       ...   ...  
307  0.083     0.064  2018  
308  0.270     0.097  2018  
309  0.224     0.106  2018  
310  0.218     0.038  2018  
311  0.149     0.076  2018  

[304 rows x 10 columns]

In [163]:
year_2018 = multiple[multiple['년도'] == 2018].sort_values('나라명')
year_2019 = multiple[multiple['년도'] == 2019].sort_values('나라명')

year_2019['전년대비 점수 증가'] = year_2019['점수'].values - year_2018['점수'].values
year_2019

year_2019[year_2019['전년대비 점수 증가'].max() == year_2019['전년대비 점수 증가']][['나라명', '전년대비 점수 증가']]

나라명  전년대비 점수 증가
144  Burundi        0.87

In [163]:
year_2018 = multiple[multiple['년도'] == 2018].sort_values('나라명')
year_2019 = multiple[multiple['년도'] == 2019].sort_values('나라명')

# 인덱스 초기화, 동일하게
year_2018.reset_index(drop=True, inplace=True)
year_2019.reset_index(drop=True, inplace=True)

# 인덱스가 같아져서 위와 다르게 values로 가져오지 않아도 됨
year_2019['전년대비 점수 증가'] = year_2019['점수'] - year_2018['점수']
year_2019

year_2019[year_2019['전년대비 점수 증가'].max() == year_2019['전년대비 점수 증가']][['나라명', '전년대비 점수 증가']]

나라명  전년대비 점수 증가
144  Burundi        0.87

## 유튜브 데이터 분석 (20점)
- 분석 내용
    - ① 컬럼의 이름을 다음과 같이 변경하시오
        ◼title : 채널명, category : 카테고리, subscriber : 구독자수, view : 조회수, video : 영상개수
    - ② ‘구독자수’ 컬럼과 ‘조회수’ 컬럼의 타입을 정수형(int64)로 변경하시오 (‘억’,’만’ 한글을 삭제 후 숫자로 변경)
    - ③ ‘영상개수’ 컬럼의 ‘,’와 ‘개’문자를 제거하고 정수형(int32)로 변경하시오.
    - ④ 인기 채널 확인하기
        ◼’구독자수’와 ‘조회수’가 많은 5개의 채널을 각각 출력하시오.
    - ⑤ ‘카테고리’가 [음악/댄스/가수]인 채널의 ‘구독자수’ 상위 5개를 출력하시오.
    - ⑥ ‘카테고리가’ [TV/방송]이거나 [게임]인 채널의 개수를 출력하시오.
    - ⑦ ‘채널명’에 ‘KBS’가 포함된 채널 명을 출력하시오.
    - ⑧ ‘카테고리’별 ‘구독자수’, ‘조회수’, ‘영상개수’의 평균을 출력하시오.

In [169]:
data = pd.read_csv('youtube_rank.csv')

In [172]:
data

채널명        카테고리   구독자수        조회수     영상개수
0                      BLACKPINK  [음악/댄스/가수]  5140만  128억5130만     319개
1                 Big Hit Labels  [음악/댄스/가수]  4550만  120억8966만     433개
2                      BANGTANTV  [음악/댄스/가수]  3870만   54억7598만   1,319개
3    Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  2650만  110억5288만     223개
4                         SMTOWN  [음악/댄스/가수]  2450만  180억7532만   3,583개
..                           ...         ...    ...        ...      ...
995                Ranking World       [미분류]    40만    1억2752만     503개
996                         급식걸즈    [취미/라이프]    40만    2억3901만     226개
997                          OCN     [TV/방송]    40만    3억4583만  10,071개
998                Bravo jamoasi       [미분류]    40만      6193만      25개
999                  덕출 : DCTVGO     [TV/방송]    40만      8249만     202개

[1000 rows x 5 columns]

① 컬럼의 이름을 다음과 같이 변경하시오


In [171]:
data.columns = ['채널명', '카테고리', '구독자수', '조회수', '영상개수']
data.columns

Index(['채널명', '카테고리', '구독자수', '조회수', '영상개수'], dtype='object')

② ‘구독자수’ 컬럼과 ‘조회수’ 컬럼의 타입을 정수형(int64)로 변경하시오 (‘억’,’만’ 한글을 삭제 후 숫자로 변경)

In [173]:
data['구독자수'] = data['구독자수'].str.replace('만', '0000', regex=False).astype('int64')

In [174]:
data['조회수'] = data['조회수'].replace(['억', '만'], ['', '0000'], regex=True).astype('int64')

In [290]:
# data['구독자수'] = data['구독자수'].str.replace('만', '', regex=False)
# data['구독자수'] = data['구독자수'].str.replace('억', '', regex=False)
# data['조회수'] = data['조회수'].str.replace('만', '', regex=False)
# data['조회수'] = data['조회수'].str.replace('억', '', regex=False)

# data['구독자수'] = data['구독자수'].astype('int64')
# data['조회수'] = data['조회수'].astype('int64')

③ ‘영상개수’ 컬럼의 ‘,’와 ‘개’문자를 제거하고 정수형(int32)로 변경하시오.

In [176]:
data['영상개수'] = data['영상개수'].replace([',', '개'], ['', ''], regex=True).astype('int32')

In [291]:
# data['영상개수'] = data['영상개수'].str.replace(',', '', regex=False)
# data['영상개수'] = data['영상개수'].str.replace('개', '', regex=False)
# data['영상개수'] = data['영상개수'].astype('int32')

④ 인기 채널 확인하기
    <blockquote> ◼’구독자수’와 ‘조회수’가 많은 5개의 채널을 각각 출력하시오.

In [177]:
data.sort_values('구독자수', ascending=False).head(5)

채널명        카테고리      구독자수          조회수  영상개수
0                    BLACKPINK  [음악/댄스/가수]  51400000  12851300000   319
1               Big Hit Labels  [음악/댄스/가수]  45500000  12089660000   433
2                    BANGTANTV  [음악/댄스/가수]  38700000   5475980000  1319
3  Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  11052880000   223
4                       SMTOWN  [음악/댄스/가수]  24500000  18075320000  3583

In [178]:
data.sort_values('조회수', ascending=False).head(5)

채널명        카테고리      구독자수          조회수   영상개수
4            SMTOWN  [음악/댄스/가수]  24500000  18075320000   3583
6      1theK (원더케이)  [음악/댄스/가수]  20900000  17860420000  13291
8  ArianaGrandeVevo  [음악/댄스/가수]  18200000  14796920000    112
0         BLACKPINK  [음악/댄스/가수]  51400000  12851300000    319
1    Big Hit Labels  [음악/댄스/가수]  45500000  12089660000    433

⑤ ‘카테고리’가 [음악/댄스/가수]인 채널의 ‘구독자수’ 상위 5개를 출력하시오.

In [294]:
data[data['카테고리'] == '[음악/댄스/가수]'].sort_values('구독자수', ascending=False).head(5)

채널명        카테고리  구독자수      조회수  영상개수
0              BLACKPINK  [음악/댄스/가수]  5140  1285130   319
1         Big Hit Labels  [음악/댄스/가수]  4550  1208966   433
2              BANGTANTV  [음악/댄스/가수]  3870   547598  1319
4                 SMTOWN  [음악/댄스/가수]  2450  1807532  3583
5  1MILLION Dance Studio  [음악/댄스/가수]  2230   575358  2205

⑥ ‘카테고리가’ [TV/방송]이거나 [게임]인 채널의 개수를 출력하시오.

In [185]:
# isin() 사용
len(data[data['카테고리'].isin(['[TV/방송]', '[게임]'])])

262

In [187]:
category = data[np.logical_or(data['카테고리'] == '[TV/방송]', data['카테고리'] == '[게임]')]
print(len(category))

262


⑦ ‘채널명’에 ‘KBS’가 포함된 채널 명을 출력하시오

In [189]:
data[data['채널명'].str.contains('KBS')][['채널명']]

채널명
12                  KBS World
46                   KBS Kpop
76              KBS Entertain
101                 KBS Drama
290                  KBS 한국방송
292         KBS Drama Classic
308           KBS HUMAN: 뭉클티비
389                  KBS News
457                KBS CoolFM
716                     KBS N
777                  KBS KONG
991  KBS Documentary [KBS 다큐]
992                    KBS 교양

⑧ ‘카테고리’별 ‘구독자수’, ‘조회수’, ‘영상개수’의 평균을 출력하시오.

In [191]:
data.groupby('카테고리').mean().round(2)

구독자수           조회수      영상개수
카테고리                                           
[BJ/인물/연예인]  1274411.76  4.101549e+08    837.74
[IT/기술/컴퓨터]   806250.00  1.766100e+08   1200.12
[TV/방송]      1219875.78  7.184834e+08   9025.13
[게임]          743564.36  4.542535e+08   2527.01
[교육/강의]       851304.35  1.772183e+08    837.91
[국내/해외/여행]    626000.00  1.866240e+08    830.20
[뉴스/정치/사회]   1226964.29  1.199936e+09  42048.09
[미분류]        1429500.00  4.090340e+08    778.05
[스포츠/운동]      932500.00  2.791892e+08   3954.92
[애완/반려동물]    1161000.00  4.213170e+08    786.25
[영화/만화/애니]    852727.27  3.185870e+08    770.18
[음식/요리/레시피]  1612045.45  4.073819e+08    830.02
[음악/댄스/가수]   3195200.00  1.091668e+09   1382.05
[자동차]         490000.00  1.856150e+08    670.00
[주식/경제/부동산]   626000.00  6.800000e+07   1026.40
[취미/라이프]      974500.00  2.043118e+08    359.32
[취미]          560000.00  1.061500e+08    237.00
[키즈/어린이]     2729157.89  1.281384e+09   1069.16
[패션/미용]       823859.65  1.043774e+08    313.16
[해외]         1595000.00  8.382533e+08   5043.50
[회사/오피셜]     2202500.00  4.966125e+08   2084.25

In [193]:
# data.groupby('카테고리')[['구독자수', '조회수', '영상개수']].mean().round(2)