In [269]:
import numpy as np

# [문제] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사람별 BMI 지수를 구하고 비만 전단계 이상인 BMI 값 확인하기

<pre>
 BMI 지수 = 몸무게(kg) / 키(M)의 제곱
 체질량지수의 범위 값에 따른 비만도 값 지정
 18.5 미만 ▶ 저체중
 18.5 ~ 22.9 ▶ 정상
 23 ~ 24.9 ▶ 비만 전단계
 25 ~ 29 ▶ 1단계 비만
 30 ~ 34.9 ▶ 2단계 비만
 35이상 ▶ 고도비만
</pre>

In [ ]:
np.set_printoptions(suppress=True, precision=2)

In [273]:
data = np.loadtxt('height_weight.txt', delimiter=',', dtype='float') # (파일이름, 분류자, 데이터타입)
print(data)

bmi = data[1] / (data[0] * 0.01) ** 2
print(bmi)

print('BMI 23이상인 사람들의 BMI')
print(bmi[bmi >= 23])

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]
BMI 23이상인 사람들의 BMI
[27.07018468 25.86122449 24.20652885 23.14392095 23.62028791 25.59220998]


# [문제] 국가건강검진 혈압혈당 데이터 분석

* '국가건강검진_혈압혈당데이터.csv' 파일 내용을 읽기 <data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float, skiprows=1)>
    - 성별: 1(남자), 2(여자)
    - 연령그룹: 1(20-24), 2(25-26),...25-74세까지 2살 간격으로 1개 그룹으로 지정, 27(74세 이상)
    - 고혈압 당뇨병 진료여부: 1(고혈압 및 당뇨진료내역 있음), 2(고혈압 진료내역 있음), 3(당뇨 진료내역 있음), 4(고혈압 및 당뇨 진료내역 없음)
    - 정상혈압: 수축기 혈압 120nnHg 미만, 이완기 혈압 80mmHg 미만
    - 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
* 전체 레코드 수와 상위 5개 데이터 확인
* 데이터 모양 확인
* 여성과 남성의 데이터 수 확인
* 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
* 정상 혈압 남자 및 여자 수 확인
* 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수

In [277]:
data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=float, skiprows=1)

In [282]:
# 전체 레코드 수와 상위 5개 데이터 확인
print(f'전체 레코드수: {data.shape[0]: ,}')
print(f'상위 5개 데이터:\n {data[:5]}')

전체 레코드수:  1,000,000
상위 5개 데이터:
 [[  1.    1.  116.   78.   94.    4.   16.6]
 [  1.    1.  100.   60.   79.    4.   22.3]
 [  1.    1.  100.   60.   87.    4.   21.9]
 [  1.    1.  111.   70.   72.    4.   20.2]
 [  1.    1.  120.   80.   98.    4.   20. ]]


In [281]:
# 데이터 모양 확인
print(data.shape[1])

7


In [149]:
# 여성과 남성의 데이터 수 확인
male = data[data[:,0] == 1]
female = data[data[:,0] == 2]
# print(f'남성의 데이터 수 : {len(male)}')
# print(f'여성의 데이터 수 : {len(female)}')
print(f'남성의 데이터 수 : {sum(data[:, 0] == 1)}개')
print(f'남성의 데이터 수 : {sum(data[:, 0] == 2)}개')

남성의 데이터 수 : 510227개
남성의 데이터 수 : 489773개


In [161]:
# 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
# 수축기혈합: SBP, 이완기혈합: DBP
male_sbp_mean = np.mean(data[data[:, 0]==1][:, 2])
print(f'남성의 수축기혈압 평균: {male_sbp_mean: .2f}')
male_dbp_mean = np.mean(data[data[:, 0]==1][:, 2])
print(f'남성의 이완기혈압 평균: {male_dbp_mean: .2f}')
female_sbp_mean = np.mean(data[data[:, 0]==2][:, 2])
print(f'여성의 수축기혈압 평균: {female_sbp_mean: .2f}')
female_dbp_mean = np.mean(data[data[:, 0]==2][:, 2])
print(f'여성의 이완기혈압 평균: {female_dbp_mean: .2f}')

# female_s = np.mean(female[:, 2])
# print(f'여성의 수축기혈압 평균: {female_s}')
# female_e = np.mean(female[:,3])
# print(f'여성의 이완기혈압 평균: {female_e}')

남성의 수축기혈압 평균:  124.28
남성의 이완기혈압 평균:  124.28
여성의 수축기혈압 평균:  119.36
여성의 이완기혈압 평균:  119.36


In [167]:
# 정상 혈압 남자 및 여자 수 확인
# 정상혈압: 수축기 혈압 120nnHg 미만, 이완기 혈압 80mmHg 미만
nbp_masking = np.logical_and(data[:, 2] < 120, data[:, 3] < 80)
nbp_data = data[nbp_masking]
print(f'정상혈합 남자 수: {sum(nbp_data[:, 0] == 1): ,}명')
print(f'정상혈합 여자 수: {sum(nbp_data[:, 0] == 2): ,}명')

정상혈합 남자 수:  158,007명
정상혈합 여자 수:  230,707명


In [169]:
# 당뇨병(diabetes) 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수
diabetes = data[data[:, 4] > 126]
print(f'당뇨병 질환 환자의 평균 BMI: {np.mean(diabetes[:,-1]): .2f}')

당뇨병 질환 환자의 평균 BMI:  25.17


# [문제] 시에틀 강수량 데이터 분석
- 'Seattle2014.csv' 파일 내용 읽기
- 강수량('PRCP')이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균강수량 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

In [517]:
data = np.loadtxt('Seattle2014.csv', delimiter=',', dtype=object, skiprows=1) # dtype=object: 전체 데이터를 문자열 형태로

In [518]:
# 강수량('PRCP')이 많은 날 상위 10일 확인
prcp = data[:, 3].astype(int)
top_prcp = np.argsort(prcp)[::-1][:10]
print(top_prcp)
print(f'강수량이 많은날 상위 10일:\n {data[top_prcp]}')

[ 63 331 122  66 294  74  46 302  86  28]
강수량이 많은날 상위 10일:
 [['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140305' '467' '0' '0' '156' '106' '39' '190' '200' '112' '157' '1'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20141128' '343' '0' '0' '128' '33' '58' '10' '10' '103' '143' '1'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140503' '333' '0' '0' '150' '89' '34' '210' '200' '98' '130' '1'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140308' '323' '0' '0' '128' '67' '27' '200' '210' '76' '103' '1'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20141022' '320' '0' '0' '156' '117' '50' '200' '130' '81' '125' '1'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140316' '277' '0' '0' '106' '44' '38' '230' '2

In [519]:
# 상위 강수량과 날짜도 같이 출력
prcp = data[:, [2, 3]].astype(int)
prcp = prcp[prcp[:, 1].argsort()][::-1][:10]
print(prcp)

[[20140305      467]
 [20141128      343]
 [20140503      333]
 [20140308      323]
 [20141022      320]
 [20140316      277]
 [20140216      264]
 [20141030      254]
 [20140328      221]
 [20140129      216]]


In [538]:
# 1월 강수량만 출력
prcp = data[:, [2,3]]
prcp_month = np.array([[date[4:6], prcp] for date, prcp_month in prcp])
jan_prcp = prcp_month[prcp_month[:, 0] == '01'][:, 1]
jan_prcp = prcp_month[prcp_month[:, 0] == '01'][:, 1].astype(int)
     
print(jan_prcp)

C:\Users\user\AppData\Local\Temp\ipykernel_12396\2768192029.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  prcp_month = np.array([[date[4:6], prcp] for date, prcp_month in prcp])


ValueError: setting an array element with a sequence.

In [537]:
# 1월에 내린 강수량의 합, 평균강수량 확인
print(f'1월 강수량 합: {np.sum(jan_prcp)}')
print(f'1월 강수량 합: {np.mean(jan_prcp):. 2f}')

1월 강수량 합: [['20140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101201401012014010120140101'
  '0000000000000000000000000000000']
 ['20140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102201401022014010220140102'
  '41414141414141414141414141414141414141414141414141414141414141']
 ['20140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103201401032014010320140103'
  '15151515151515151515151515151515151515151515151515151515151515']
 ['2014010420140104201401042014010420140104201401042014010

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [389]:
# 1년동안 강수량이 40미만으로 내린 날이 몇일인가?
prcp = data[:, 3].astype(int)
under_40 = prcp[prcp < 40]
print(f'40 미만으로 내린 날 수: {len(under_40)}일')

40 미만으로 내린 날 수: 277일


# [문제] 영화 평점 분석
- 'ratings.dat' 파일 내용 읽기 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인(크기, 차원)
- 전체 데이터 평점 구하기
- 사용자 아이디 1인 데이터 출력하기
- 사용자 아이디 1인 사람의 평점 평균 구하기
- 각 사용자별 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

In [489]:
data = np.loadtxt('ratings.dat', delimiter='::', dtype=int)

In [472]:
# 상위 10개 데이터 출력하기
top_data = data[::-1][:10]
print(top_data)

[[     6040      1097         4 956715569]
 [     6040      1096         4 956715648]
 [     6040       562         5 956704746]
 [     6040      1094         5 956704887]
 [     6040      1091         1 956716541]
 [     6040      1090         3 956715518]
 [     6040      1089         4 956704996]
 [     6040      1080         4 957717322]
 [     6040      2028         5 956704519]
 [     6040      2022         5 956716207]]


In [473]:
# 데이터 정보 확인(크기, 차원)
print(f'데이터 크기: {data.shape[0]}')
print(f'데이터 차원: {data.ndim}')

데이터 크기: 1000209
데이터 차원: 2


In [499]:
# 전체 데이터 평균 평점 구하기
rating = np.mean(data[:, 2])
print(rating)

3.581564453029317


In [446]:
# 사용자 아이디 1인 데이터 출력하기
user_1 = data[data[: , 0] == 1]
print(user_1)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1

In [474]:
# 사용자 아이디 1인 사람의 평균 평점 구하기
rating_avg = np.mean(user_1[:,2])
print(rating_avg)

4.188679245283019


In [506]:
# 각 사용자별 평균 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
user_ids = np.unique(data[:, 0])
print(f'전체 사용자 수: {len(user_ids): ,}명')

user_avg_rating = [ [id, np.mean(data[data[:, 0] == id][:, 2])] for id in user_ids]
for id, avg_rating in user_avg_rating[:10]: # 10번 회원까지만 출력
    print(f'{id} : {avg_rating: .2f}명')

전체 사용자 수:  6,040명
1 :  4.19명
2 :  3.71명
3 :  3.90명
4 :  4.19명
5 :  3.15명
6 :  3.90명
7 :  4.32명
8 :  3.88명
9 :  3.74명
10 :  4.11명


In [509]:
np.set_printoptions(suppress=True, precision=2) # precision: 소수점 자리

In [514]:
# 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기
user_avg_rating = np.array(user_avg_rating)
user_avg_rating[:10]
print(f'평균 평점이 4점 이상인 유저 수: {sum(user_avg_rating[:, 1] >= 4): ,}명')

평균 평점이 4점 이상인 유저 수:  1,544명
